version: '3'

services:
  flask:
    build: 
      context: .
      dockerfile: ./compose/Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - ./:/app
    env_file:
      - ./config/.env
    depends_on:
      - redis
      - db
    stdin_open: true
    tty: true
    restart: on-failure
  
  db:
    image: postgres:13
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    expose:
      - "5432"
  
  redis:
    image: redis:7-alpine
  
  celery_worker:
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    volumes:
      - ./:/app
    env_file:
      - ./config/.env
    command: ['celery', '-A', 'app', 'worker', '-l', 'info']
    depends_on:
      - redis
  