"""empty message

Revision ID: 49dae90cb44c
Revises: ce3b3d0f05b8
Create Date: 2023-11-23 12:28:31.456498

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "49dae90cb44c"
down_revision = "ce3b3d0f05b8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("_password", sa.String(length=100), nullable=False)
        )
        batch_op.add_column(sa.Column("_salt", sa.String(length=100), nullable=False))
        batch_op.drop_column("password")
        batch_op.drop_column("observes")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "observes", sa.VARCHAR(length=100), autoincrement=False, nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                "password", sa.VARCHAR(length=100), autoincrement=False, nullable=False
            )
        )
        batch_op.drop_column("_salt")
        batch_op.drop_column("_password")

    # ### end Alembic commands ###
