"""Remove valid_for and owner fields from InvitationCode model

Revision ID: 9b06356e3d78
Revises: d022cc46b3a2
Create Date: 2024-01-22 13:12:42.013266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9b06356e3d78"
down_revision = "d022cc46b3a2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("invitation_code", schema=None) as batch_op:
        batch_op.drop_column("valid_for")
        batch_op.drop_column("owner")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("invitation_code", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "owner", sa.VARCHAR(length=100), autoincrement=False, nullable=False
            )
        )
        batch_op.add_column(
            sa.Column("valid_for", sa.INTEGER(), autoincrement=False, nullable=False)
        )

    # ### end Alembic commands ###
