"""empty message

Revision ID: ce3b3d0f05b8
Revises: 
Create Date: 2023-11-16 15:24:27.557445

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ce3b3d0f05b8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("password", sa.String(length=100), nullable=False),
        sa.Column("activated", sa.Boolean(), nullable=False),
        sa.Column("observes", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
    )
    op.create_table(
        "follow",
        sa.Column("follower_id", sa.Integer(), nullable=False),
        sa.Column("followed_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["followed_id"], ["user.id"], name=op.f("fk_follow_followed_id_user")
        ),
        sa.ForeignKeyConstraint(
            ["follower_id"], ["user.id"], name=op.f("fk_follow_follower_id_user")
        ),
        sa.PrimaryKeyConstraint("follower_id", "followed_id", name=op.f("pk_follow")),
    )
    op.create_table(
        "invitation_code",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column("owner", sa.String(length=100), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("valid_for", sa.Integer(), nullable=False),
        sa.Column("disabled", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_invitation_code_user_id_user")
        ),
        sa.PrimaryKeyConstraint("uuid", name=op.f("pk_invitation_code")),
    )
    op.create_table(
        "message",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("content", sa.String(length=500), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_message_user_id_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("message")
    op.drop_table("invitation_code")
    op.drop_table("follow")
    op.drop_table("user")
    # ### end Alembic commands ###
