"""empty message

Revision ID: d022cc46b3a2
Revises: fc7c9d000329
Create Date: 2024-01-11 13:26:54.477841

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d022cc46b3a2"
down_revision = "fc7c9d000329"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("activation_code", sa.String(length=40), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("activation_code")

    # ### end Alembic commands ###
