"""Increase salt length, password length to fit hash

Revision ID: d56d6b75f3ec
Revises: 20ef38e07a4d
Create Date: 2024-01-02 10:50:06.326060

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d56d6b75f3ec"
down_revision = "20ef38e07a4d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "_password",
            existing_type=sa.VARCHAR(length=100),
            type_=sa.String(length=200),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "_salt",
            existing_type=sa.VARCHAR(length=100),
            type_=sa.String(length=200),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "_salt",
            existing_type=sa.String(length=200),
            type_=sa.VARCHAR(length=100),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "_password",
            existing_type=sa.String(length=200),
            type_=sa.VARCHAR(length=100),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
